name: 'Setup git'
description: 'Setup a git environment ready to commit and push'

runs:
  using: 'composite'
  steps:
    - run: npx semantic-release
      shell: bash
      env:
        GIT_AUTHOR_NAME: 'Hoid'
        GIT_COMMITTER_NAME: 'Hoid'
        GIT_AUTHOR_EMAIL: 'hoid@zefiros.io'
        GIT_COMMITTER_EMAIL: 'hoid@zefiros.io'
    - run: npx node-standards make-release
      shell: bash
      if: github.ref == 'refs/heads/next'
