name: "Release using semantic release"

inputs:
  dry_run:
    description: Enable dry-run flag on semantic-release
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - run: npx semantic-release ${{ inputs.dry_run == 'false' && '' || '--dry-run' }}
      shell: bash
      env:
        GIT_AUTHOR_NAME: "Hoid"
        GIT_COMMITTER_NAME: "Hoid"
        GIT_AUTHOR_EMAIL: "hoid@zefiros.io"
        GIT_COMMITTER_EMAIL: "hoid@zefiros.io"
