name: Reusable Typescript build pipeline

on:
  workflow_call:
    inputs:
      artifact_path:
        description: Path of the build artifacts (multi-line)
        type: string
        required: false
        default: |
          .main.js
          .main.js.map
          index.d.ts
          src/**/*.d.ts
      artifact_name:
        description: Custom name of the build artifacts
        type: string
        required: false
        default: build-artifacts
    outputs:
      artifact_name:
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: zefiros-software/node-standards/.github/actions/setup-node@next
      - run: npm run build
      - name: Dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
      - id: set_artifact_name
        run: echo '::set-output name=artifact_name::${{ inputs.artifact_name }}'

    outputs:
      artifact_name: ${{ steps.set_artifact_name.outputs.artifact_name }}
