name: Reusable release pipeline for NodeJS projects

on:
  workflow_call:
    inputs:
      build_artifact_name:
        description: Name of the build artifact
        type: string
        required: true
      build_artifact_path:
        required: false
        type: string
      publish_docs:
        description: Publish documentation folder to github pages
        type: string
        required: false
        default: 'true'
      git_author:
        description: The name of the git committer
        type: string
        required: false
        default: 'Hoid'
      git_email:
        description: The git committer email address
        type: string
        required: false
        default: 'hoid@zefiros.io'
    secrets:
      GITHUB_NPM_TOKEN:
        description: Token to install GitHub packages with
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download node standards
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ inputs.build_artifact_path }}
      - uses: zefiros-software/node-standards/.github/actions/setup-node@next
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
      - uses: zefiros-software/node-standards/.github/actions/release@feat/typedoc
        with:
          dry_run: ${{ (github.ref == 'refs/heads/next' || github.ref == 'refs/heads/main') && 'false' || 'true' }}
        env:
          # Uses GITHUB_TOKEN for publish permissions
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  documentation:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish_docs == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: zefiros-software/node-standards/.github/actions/setup-node@next
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
      - run: npm run build:docs
      - run: |
          mkdir -p .docs
          cd .docs
          git init -b gh-pages
          git add --all
          git commit -m 'chore: deploy docs'
          git remote add origin ${{ github.repositoryUrl }}
          git push -u origin gh-pages
        env:
          GIT_AUTHOR_NAME: ${{ inputs.git_author }}
          GIT_COMMITTER_NAME: ${{ inputs.git_author }}
          GIT_AUTHOR_EMAIL: ${{ inputs.git_email }}
          GIT_COMMITTER_EMAIL: ${{ inputs.git_email }}
